/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cursowaworkv12;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author ZEUS
 */
public class MainFrame extends javax.swing.JFrame {
    //addProduct addprd = null;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooserProduct = new javax.swing.JFileChooser();
        jMenuItem8 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        jFileChooserProduct.setDialogTitle("Вибір файлу");

        jMenuItem8.setText("jMenuItem8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        jButton4.setText("Техніка");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Продукти");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jMenu3.setText("Файли");

        jMenuItem1.setText("Завантажити товари");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Завантажити техніку");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Заватнажити продукти");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem5.setText("Завантажити файл");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Ввід даних");

        jMenuItem4.setText("Додати товар");
        jMenuItem4.setEnabled(false);
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem6.setText("Додати техніку");
        jMenuItem6.setEnabled(false);
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Додати продукт");
        jMenuItem7.setEnabled(false);
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
         String[] columnNames = {"Код", "Назва", "Країна-виробник", "Ціна"};
        
        int returnVal = jFileChooserProduct.showOpenDialog(this);
    if (returnVal == jFileChooserProduct.APPROVE_OPTION) {
        CursowaWorkV12.fileProduct = jFileChooserProduct.getSelectedFile();
             try {
                 CursowaWorkV12.productsArray =  new ArrayList(CursowaWorkV12.readProducts(CursowaWorkV12.fileProduct));
             } catch (Exception ex) {
                 JOptionPane.showMessageDialog(this, "Файл пошкоджений або містить помилку!");   
             }
        Object[][] data = new String[CursowaWorkV12.productsArray.size()+1][4];
       Product temp;
       for(int i = 0; i < CursowaWorkV12.productsArray.size(); i++){
       temp = (Product) CursowaWorkV12.productsArray.get(i);
      data[i][0] = String.valueOf(temp.number);
       data[i][1] = temp.name;
       data[i][2] = temp.country;
       data[i][3] = String.valueOf(temp.price);
       }
 jTable1.setModel(new javax.swing.table.DefaultTableModel(data, columnNames));

      
    }//GEN-LAST:event_jMenuItem1ActionPerformed
   }
    
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
     SimpleDateFormat ft = new SimpleDateFormat("dd.MM.yyyy", Locale.getDefault());
         String[] columnNames = {"Код", "Назва", "Країна-виробник", "Ціна", "Гарантія", "Габарити", "Вага", "масив комплектації"};
        
        int returnVal = jFileChooserProduct.showOpenDialog(this);
    if (returnVal == jFileChooserProduct.APPROVE_OPTION) {
        CursowaWorkV12.fileElectronic = jFileChooserProduct.getSelectedFile();
             try {
                 CursowaWorkV12.electronicsArray =  new ArrayList(CursowaWorkV12.readElectronics(CursowaWorkV12.fileElectronic));
             } catch (Exception ex) { 
                 JOptionPane.showMessageDialog(this, "Файл пошкоджений або містить помилку!");
            }
        Object[][] data = new String[CursowaWorkV12.electronicsArray.size()+1][8];
       Electronic temp;
       for(int i = 0; i < CursowaWorkV12.electronicsArray.size(); i++){
       temp = (Electronic) CursowaWorkV12.electronicsArray.get(i);
      data[i][0] = String.valueOf(temp.number);
       data[i][1] = temp.name;
       data[i][2] = temp.country;
       data[i][3] = String.valueOf(temp.price);
       data[i][4] = ft.format(temp.getSimpleDateFormat());
       data[i][5] = String.valueOf(temp.gabarits[0])+"x"+String.valueOf(temp.gabarits[1])+"x"+String.valueOf(temp.gabarits[2]);
       data[i][6] = String.valueOf(temp.masa);
       StringBuilder stb = new StringBuilder();
        for(int x = 0; x < temp.complectMas.size(); x++){
            stb.append(temp.complectMas.get(x)+" ");
       }
        data[i][7] =  stb.toString();
  
    }                          
        
   jTable1.setModel(new javax.swing.table.DefaultTableModel(data, columnNames));  
    jButton4.setEnabled(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    }
    
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
     SimpleDateFormat ft = new SimpleDateFormat("dd.MM.yyyy", Locale.getDefault());
        String[] columnNames = {"Код", "Назва", "Країна-виробник", "Ціна", "жири", "білки", "вуглеводи", "генна модифікація", "термін споживання" , "масив вітамінів"};
      int returnVal = jFileChooserProduct.showOpenDialog(this);
      if (returnVal == jFileChooserProduct.APPROVE_OPTION) {
        CursowaWorkV12.fileEat = jFileChooserProduct.getSelectedFile();
         CursowaWorkV12.eatArray =  new ArrayList(CursowaWorkV12.readEats(CursowaWorkV12.fileEat));
        Object[][] data = new String[CursowaWorkV12.eatArray.size()+1][10];
       Eat temp;
       for(int i = 0; i < CursowaWorkV12.eatArray.size(); i++){
       temp = (Eat) CursowaWorkV12.eatArray.get(i);
      data[i][0] = String.valueOf(temp.number);
       data[i][1] = temp.name;
       data[i][2] = temp.country;
       data[i][3] = String.valueOf(temp.price);
       data[i][4] = String.valueOf(temp.fat);
       data[i][5] = String.valueOf(temp.white);
       data[i][6] = String.valueOf(temp.carbohydrates);
       data[i][7] = String.valueOf(temp.genMod);
       data[i][8] = ft.format(temp.getEatTermEnd());
       
       StringBuilder stb = new StringBuilder();
        for(int x = 0; x < temp.vitaminsMas.size(); x++){
            stb.append(temp.vitaminsMas.get(x)+" ");
       }
        data[i][9] =  stb.toString();
    }                          
   jTable1.setModel(new javax.swing.table.DefaultTableModel(data, columnNames));  
    jButton5.setEnabled(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    }
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
    //addprd = new createProduct();
   // addprd.setVisible(true);
   // addprd.pack();
////        AddProduct addProdu=  new AddProduct();
////                addProdu.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         SimpleDateFormat ft = new SimpleDateFormat("dd.MM.yyyy", Locale.getDefault());
         String[] columnNames = {"Код", "Назва", "Країна-виробник", "Ціна", "Гарантія", "Габарити", "Вага", "масив комплектації"};
         Object[][] data = new String[CursowaWorkV12.electronicsArray.size()+1][8];
       Electronic temp;
       for(int i = 0; i < CursowaWorkV12.electronicsArray.size(); i++){
       temp = (Electronic) CursowaWorkV12.electronicsArray.get(i);
      data[i][0] = String.valueOf(temp.number);
       data[i][1] = temp.name;
       data[i][2] = temp.country;
       data[i][3] = String.valueOf(temp.price);
       data[i][4] = ft.format(temp.getSimpleDateFormat());
       data[i][5] = String.valueOf(temp.gabarits[0])+"x"+String.valueOf(temp.gabarits[1])+"x"+String.valueOf(temp.gabarits[2]);
       data[i][6] = String.valueOf(temp.masa);
       StringBuilder stb = new StringBuilder();
        for(int x = 0; x < temp.complectMas.size(); x++){
            stb.append(temp.complectMas.get(x)+" ");
       }
        data[i][7] =  stb.toString();
  
    }                          
        
   jTable1.setModel(new javax.swing.table.DefaultTableModel(data, columnNames));
 //    jTextField3.setText("");
    jButton4.setEnabled(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
  SimpleDateFormat ft = new SimpleDateFormat("dd.MM.yyyy", Locale.getDefault());
        String[] columnNames = {"Код", "Назва", "Країна-виробник", "Ціна", "жири", "білки", "вуглеводи", "генна модифікація", "термін споживання" , "масив вітамінів"};
         Object[][] data = new String[CursowaWorkV12.eatArray.size()+1][10];
       Eat temp;
       for(int i = 0; i < CursowaWorkV12.eatArray.size(); i++){
       temp = (Eat) CursowaWorkV12.eatArray.get(i);
      data[i][0] = String.valueOf(temp.number);
       data[i][1] = temp.name;
       data[i][2] = temp.country;
       data[i][3] = String.valueOf(temp.price);
       data[i][4] = String.valueOf(temp.fat);
       data[i][5] = String.valueOf(temp.white);
       data[i][6] = String.valueOf(temp.carbohydrates);
       data[i][7] = String.valueOf(temp.genMod);
       data[i][8] = ft.format(temp.getEatTermEnd());
       
       StringBuilder stb = new StringBuilder();
        for(int x = 0; x < temp.vitaminsMas.size(); x++){
            stb.append(temp.vitaminsMas.get(x)+" ");
       }
        data[i][9] =  stb.toString();
    }                          
   jTable1.setModel(new javax.swing.table.DefaultTableModel(data, columnNames));
    jButton5.setEnabled(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
         int returnVal = jFileChooserProduct.showOpenDialog(this);
      if (returnVal == jFileChooserProduct.APPROVE_OPTION) {
      File tmp = jFileChooserProduct.getSelectedFile();
       BufferedReader in;
         String check_class = null;
             try {
                 in = new BufferedReader(new FileReader(tmp.getAbsoluteFile()));
                 check_class = in.readLine();
             } catch (FileNotFoundException ex) {
                 Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
             } catch (IOException ex) {
                 Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
             }
      if(check_class.equals("Eats")){
          SimpleDateFormat ft = new SimpleDateFormat("dd.MM.yyyy", Locale.getDefault());
           String[] columnNames = {"Код", "Назва", "Країна-виробник", "Ціна", "жири", "білки", "вуглеводи", "генна модифікація", "термін споживання" , "масив вітамінів"};
          try {
          CursowaWorkV12.eatArray =  new ArrayList(CursowaWorkV12.readEats(tmp));
        Object[][] data = new String[CursowaWorkV12.eatArray.size()+1][10];
       Eat temp;
       for(int i = 0; i < CursowaWorkV12.eatArray.size(); i++){
       temp = (Eat) CursowaWorkV12.eatArray.get(i);
      data[i][0] = String.valueOf(temp.number);
       data[i][1] = temp.name;
       data[i][2] = temp.country;
       data[i][3] = String.valueOf(temp.price);
       data[i][4] = String.valueOf(temp.fat);
       data[i][5] = String.valueOf(temp.white);
       data[i][6] = String.valueOf(temp.carbohydrates);
       data[i][7] = String.valueOf(temp.genMod);
       data[i][8] = ft.format(temp.getEatTermEnd());
       
       StringBuilder stb = new StringBuilder();
        for(int x = 0; x < temp.vitaminsMas.size(); x++){
            stb.append(temp.vitaminsMas.get(x)+" ");
       }
        data[i][9] =  stb.toString();
    }                          
   jTable1.setModel(new javax.swing.table.DefaultTableModel(data, columnNames));
          } catch (Exception ex) {
              Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
          }
      }
      if(check_class.equals("Electronics")){
       SimpleDateFormat ft = new SimpleDateFormat("dd.MM.yyyy", Locale.getDefault());
         String[] columnNames = {"Код", "Назва", "Країна-виробник", "Ціна", "Гарантія", "Габарити", "Вага", "масив комплектації"};
         
          try {
              CursowaWorkV12.electronicsArray =  new ArrayList(CursowaWorkV12.readElectronics(tmp));
          } catch (Exception ex) {
              Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
          }
        Object[][] data = new String[CursowaWorkV12.electronicsArray.size()+1][8];
       Electronic temp;
       for(int i = 0; i < CursowaWorkV12.electronicsArray.size(); i++){
       temp = (Electronic) CursowaWorkV12.electronicsArray.get(i);
      data[i][0] = String.valueOf(temp.number);
       data[i][1] = temp.name;
       data[i][2] = temp.country;
       data[i][3] = String.valueOf(temp.price);
       data[i][4] = ft.format(temp.getSimpleDateFormat());
       data[i][5] = String.valueOf(temp.gabarits[0])+"x"+String.valueOf(temp.gabarits[1])+"x"+String.valueOf(temp.gabarits[2]);
       data[i][6] = String.valueOf(temp.masa);
       StringBuilder stb = new StringBuilder();
        for(int x = 0; x < temp.complectMas.size(); x++){
            stb.append(temp.complectMas.get(x)+" ");
       }
        data[i][7] =  stb.toString();
    }                          
   jTable1.setModel(new javax.swing.table.DefaultTableModel(data, columnNames)); 
      }
      }
    }//GEN-LAST:event_jMenuItem5ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JFileChooser jFileChooserProduct;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
